name: Build & Deploy Panikzettel
on:
  workflow_run:
    workflows: ["timestamp"]
    types: [completed]
    branches:
      - "main"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Git Safe Dir
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Restore build files as cache
        id: latex-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ./build
          restore-keys: |
            latex-cache-${{ runner.os }}
          key: latex-cache-${{ runner.os }}-${{ hashFiles('**.tex', 'deps/**', 'img/**') }}
      - name: Compile with TexLive
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            apk add git
            git config --global --add safe.directory /home/runner/work/panikzettel/panikzettel
            make clean
            make --keep-going all
      # Utilize Latex caching
      - name: Save build files as cache
        id: latex-cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ./build/
          key: ${{ steps.latex-cache-restore.outputs.cache-primary-key }}
      - name: Archive Latex artifacts
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          name: latex-artifacts
          path: ./build/*.pdf
  build_typst:
    runs-on: ubuntu-latest
    container: ghcr.io/typst/typst:0.14.0
    steps:
      - name: Setup environment
        run: |
          apk add make
          apk add bash
          apk add git
          apk add gpg
          apk add tar
          apk add curl
          apk add fc-cache
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Git Safe Dir
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Install fonts
        run: |
          ./scripts/install-fonts.sh
      - name: Build Typst
        #if: github.event_name == 'push' && (github.event.head_commit.message =~ /.*\.tex|.*\.cls|Makefile|scripts\// || github.event.ref == 'refs/heads/main')
        run: |
          make typst
      - name: Archive Typst artifacts
        #if: github.event_name == 'push' && (github.event.head_commit.message =~ /.*\.tex|.*\.cls|Makefile|scripts\// || github.event.ref == 'refs/heads/main')
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          name: typst-artifacts
          path: ./build/*.pdf
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    needs:
      - build_latex
      - build_typst
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      # we must download the artifacts here
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          #download all artifacts => name=none
          path: build/
          merge-multiple: true
      - name: auth
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: htwr-aachen
          workload_identity_provider: "projects/984825600619/locations/global/workloadIdentityPools/htwr-identity-pool/providers/panikzettel"
      - name: Deploy Panikzettel
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          project_id: htwr-aachen
          path: build
          destination: ${{vars.GCP_BUCKET_URL}}
          parent: false # dont upload build directory
          headers: |-
            cache-control: 'public, max-age=3600'
      - name: Deploy Panikzettel Metadata
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          project_id: htwr-aachen
          path: metadata.json
          destination: ${{vars.GCP_BUCKET_URL}}
          parent: false # dont upload build directory
          headers: |-
            cache-control: 'public, max-age=3600'
