name: timestamp
on:
  push:
    branches:
      - main

jobs:
  timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we want the full history

      - name: Versionize
        run: |
          ./scripts/versionize.sh metadata.json

      - name: Add & Commit & Push metadata.json
        run: |
          if git diff --name-only | grep -q "metadata.json"; then
            git add metadata.json

            git config --global user.name "GITHUB-TIMESTAMP-ACTION"
            git config --global user.email "GITHUB-TIMESTAMP-ACTION@users.noreply.github.com"
            git commit -m "chore(timestamp): Update metadata timestamps"
            git push
          else
            echo "No changes continuing"
          fi
